{"name": "Провека ошибки 401 при получении списка заказов неавторизованным пользователем", "status": "passed", "description": "Ошибка cписка заказов неавторизованного пользователя", "steps": [{"name": "Создать заказ", "status": "passed", "parameters": [{"name": "headers", "value": "None"}, {"name": "ingredients", "value": "{'ingredients': ['61c0c5a71d1f82001bdaaa6f', None, '61c0c5a71d1f82001bdaaa6d']}"}], "start": 1730541599279, "stop": 1730541599794}, {"name": "Создать заказ", "status": "passed", "parameters": [{"name": "headers", "value": "None"}, {"name": "ingredients", "value": "{'ingredients': ['61c0c5a71d1f82001bdaaa6f', None, '61c0c5a71d1f82001bdaaa6d']}"}], "start": 1730541599795, "stop": 1730541600304}, {"name": "Получить все заказы конкретного пользователя", "status": "passed", "parameters": [{"name": "headers", "value": "None"}], "start": 1730541600305, "stop": 1730541600824}], "start": 1730541599278, "stop": 1730541600825, "uuid": "d026b0f9-3c3a-48db-a7b0-610fdca1bd4c", "historyId": "113954da7b8984950366cbd5d09cd418", "testCaseId": "113954da7b8984950366cbd5d09cd418", "fullName": "tests.test_receiving_order_user.TestReceivUserOrders#test_reseiv_orders_without_authorization_user", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_receiving_order_user"}, {"name": "subSuite", "value": "TestReceivUserOrders"}, {"name": "host", "value": "DESKTOP-0RIL4P0"}, {"name": "thread", "value": "11480-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_receiving_order_user"}]}